import type { Report } from '../types/report';

interface LeftRailProps {
  reports: Report[];
  activeReportId: string | null;
  onSelectReport: (slug: string) => void;
  isLoading?: boolean;
}

export function LeftRail({ reports, activeReportId, onSelectReport, isLoading = false }: LeftRailProps) {
  const ReportItem = ({ report }: { report: Report }) => {
    const isActive = report.id === activeReportId;
    
    return (
      <button
        onClick={() => onSelectReport(report.slug)}
        className={`
          group w-full text-left p-4 rounded-xl transition-colors-smooth relative overflow-hidden
          ${isActive 
            ? 'bg-surface_elevated' 
            : 'bg-surface_container_high hover:bg-surface_container_highest'
          }
        `}
      >
        {/* Subtle gradient overlay on hover */}
        <div className={`
          absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300
          ${!isActive && 'gradient-primary-subtle'}
        `} />
        
        <div className="relative z-10">
          {/* Date badge */}
          <div className="flex items-center justify-between mb-2">
            <time className={`
              text-xs font-manrope font-semibold uppercase tracking-wider
              ${isActive ? 'text-primary' : 'text-on_surface_dim'}
            `}>
              {report.date.toLocaleDateString('en-GB', { 
                day: 'numeric', 
                month: 'short',
                year: 'numeric'
              })}
            </time>
            
            {report.isLatest && (
              <span className="px-2 py-0.5 bg-primary/20 text-primary text-[10px] font-bold uppercase tracking-wider rounded">
                New
              </span>
            )}
          </div>
          
          {/* Report title excerpt */}
          <div className={`
            text-sm font-manrope leading-snug
            ${isActive ? 'text-on_surface font-medium' : 'text-on_surface_variant'}
          `}>
            AI Jobs - Edinburgh
          </div>
          
          {/* Active indicator */}
          {isActive && (
            <div className="absolute left-0 top-1/2 -translate-y-1/2 w-1 h-8 bg-primary rounded-r" />
          )}
        </div>
      </button>
    );
  };

  return (
    <aside className="w-80 bg-surface_container h-screen overflow-y-auto flex flex-col scrollbar-thin">
      {/* Header */}
      <div className="p-6 pb-4">
        <div className="flex items-baseline gap-3 mb-1">
          <h2 className="text-2xl font-newsreader text-on_surface font-light tracking-tight">
            Reports
          </h2>
          {reports.length > 0 && (
            <span className="text-sm font-manrope text-on_surface_dim">
              {reports.length}
            </span>
          )}
        </div>
        <p className="text-xs text-on_surface_dim font-manrope mt-1">
          Daily AI job intelligence
        </p>
      </div>
      
      {/* Reports list */}
      <div className="flex-1 px-4 pb-6">
        {isLoading ? (
          <div className="space-y-3">
            {[1, 2, 3].map(i => (
              <div key={i} className="bg-surface_container_high rounded-xl p-4 animate-pulse">
                <div className="h-3 bg-surface_container_highest rounded w-24 mb-3" />
                <div className="h-4 bg-surface_container_highest rounded w-full" />
              </div>
            ))}
          </div>
        ) : reports.length > 0 ? (
          <div className="space-y-2">
            {reports.map(report => (
              <ReportItem key={report.id} report={report} />
            ))}
          </div>
        ) : (
          <div className="card-elevated p-8 text-center mt-8">
            <div className="w-12 h-12 mx-auto mb-4 rounded-full bg-surface_container_highest flex items-center justify-center">
              <svg className="w-6 h-6 text-on_surface_dim" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <h3 className="text-sm font-manrope font-semibold text-on_surface mb-2">
              No Reports Yet
            </h3>
            <p className="text-xs text-on_surface_dim leading-relaxed">
              Reports will appear here as they're generated by the autonomous job intelligence system.
            </p>
          </div>
        )}
      </div>
    </aside>
  );
}
